import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import Navbar from '@/app/universal/Navbar';
import Footer from '@/app/universal/Footer';
import {Anonymous_Pro} from 'next/font/google'

export const font = Anonymous_Pro({
  subsets: ['latin'],
  weight: ['400', '700']
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});{}

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " Bibash Dev",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
 <body
       className={font.className}
      >
        <ThemeProvider attribute="class"defaultTheme= "system" enableSystem>
          <Navbar />
        {children}

          <Footer />

        </ThemeProvider>
      </body>
     
    </html>
  );
}
